# Generated by Django 5.2.7 on 2025-11-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadjob',
            name='download_type',
            field=models.CharField(default='video', max_length=10),
        ),
        migrations.AddField(
            model_name='downloadjob',
            name='quality',
            field=models.CharField(default='720p', max_length=10),
        ),
    ]
